services:
  bot:
    build: .
    container_name: tg_rag_bot
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      AUTHORIZATION_KEY: ${AUTHORIZATION_KEY}
      PATH_MESSAGES: ${PATH_MESSAGES:-/app/data/test.txt}
      PATH_BOUQUETS: ${PATH_BOUQUETS:-/app/data/bouquets.json}
      PATH_SYSTEM_PROMPT: ${PATH_SYSTEM_PROMPT:-/app/prompts/system_prompt.txt}
      PYTHONUNBUFFERED: "1"
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data:/app/data
      - ./prompts:/app/prompts
      - ./logs:/app/logs